mysite/base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.i18n import i18n_patterns

from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    #path('myauth/', include('myauth.urls'))
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),

    
   path(
       "sitemap.xml",
       sitemap,
       {"sitemaps": sitemaps},
       name="django.contrib.sitemaps.views.sitemap",
   ),
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)
urlpatterns.append(
    path("__debug__/", include("debug_toolbar.urls"))
)

mysite/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailView,
    ProductsListView,
    OrderListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductViewSet,
    ProductsDataExportView,
    )

app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/export/", ProductsDataExportView.as_view(), name="product_export"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-arhive/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order_details"),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )

class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продовать в Интернет-магазине

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]
        #verbose_name_plural = "products"

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)
    
# Если нигде кроме админки не используется, то можем перенести туда
    #@property
    #def description_short(self) -> str:
    #    if len(self.description) < 48:
    #        return self.description
    #    return self.description[:48] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"
    
def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True) 



class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm, ImageField, ClearableFileInput, Form, FileField

#from django.core import validators

from .models import Product

#class ProductForm(forms.Form):
#    name = forms.CharField(max_length=100)
#    price = forms.DecimalField(min_value=1, max_value=100000, label="Цена продукта", decimal_places=2)
#    description = forms.CharField(label="Product description",
#                                   widget=forms.Textarea(attrs={"rows":5}),
#                                   validators=[validators.RegexValidator(
#                                       regex=r"great",
#                                       message="Должно быть определенное слово"
#                                   )
#                                   ]
#                                )

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    image = ImageField(
        widget=ClearableFileInput(attrs={"multiple": True})
    )
  

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "name",

class CSVImportForm(Form):
    csv_file = FileField()

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view для интернет-магазина: по товарам, заказам и т.д.
"""

# from typing import Any
import logging

from csv import DictWriter

from django.contrib.auth.models import Group
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.views import View
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin,
                                        UserPassesTestMixin)
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from .forms import ProductForm, GroupForm
from .models import Product, Order, ProductImage
from .serializers import ProductSerializer

log = logging.getLogger(__name__)

class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товаров
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response

class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse: 
        products = [
            ('laptop', 1999),
            ('Desktop', 2999)
        ]
        context = {
            "products": products,
            "items": 6,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        return render(request, 'shopapp/shop-index.html', context=context)

class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)
    
    def post(self, request:HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)
        
class ProductDetailView(DetailView):
    template_name = 'shopapp/product-detail.html'
#    model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = 'product'
    
    
class ProductsListView(ListView): 
    template_name = 'shopapp/products-list.html'
    #model = Product
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)
    

class ProductCreateView(UserPassesTestMixin, CreateView):  
    def test_func(self):
        # return self.request.user.groups.filter(name="secret-group").exits()
        return self.request.user.is_superuser
    model = Product
#Если указывать здесь поля, то класс в форме не нужен  
#    form_class =  ProductForm     
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

class ProductUpdateView(UpdateView):
    model = Product  
#    fields = "name", "price", "description", "discount", "preview"
    #template_name = "product_update_form"
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:product_detail", 
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response          
                         


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")
# Если нужно не удалить, а поставить признак удаления

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)
        

class OrderListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects.select_related("user").prefetch_related("products").all()
    )


def orders_list(request: HttpRequest):
    context = {
        "orders": Order.objects.select_related("user").prefetch_related("products").all(),
    }
    return render(request, 'shopapp/order-list.html', context=context)

class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects.select_related("user").prefetch_related("products").all()
    )

class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by('pk').all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        elem = products_data[0]
        name = elem["name"]
        print("name:", name)
        return JsonResponse({"products": products_data})

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock  %}
    </title>
</head>
<body>
  {% block  body %}
    Base body
  {% endblock  %}  

  <div>
    {% now 'H:i' %}
  </div>
  <div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
  </div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-product.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create product
{% endblock  %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}
            
            <button type="submit">
                Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url "shopapp:products_list" %}"
        >List of products</a>
    </div>
{% endblock  %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends "shopapp/base.html" %}

{% block  title%}
    Grous List
{% endblock  %}

{% block body %}
   <h1>Groups:</h1> 
   <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
   </div>
   <div>
    {% if not groups %}
        <h3>No groups yet</h3>
        {% else %}
        <ul>

            {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                         <li>
                            {{ permission.name}}
                            (<code>{{ permission.codename}}</code>)
                         </li>
                        {% endfor %}
                    </ul>
                    
                </li> 
            {% endfor %}

        </ul>
    {% endif %}
    
   </div>
{% endblock  %}

mysite/shopapp/templates/shopapp/order-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order List
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if orders %}
    <div>
        {% for order in orders %}
            <div>
                <p>{% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode}}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Product in order:
                    <ul>
                      {% for product in order.products.all  %}
                         <li>{{ product.name }}</li>
                      {% endfor %}  
                    </ul>
                </div>
            </div>
        
        {% endfor %}
    </div>
  {% else %}
    <h3>No order yet</h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock  %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
        <p>{% firstof object.user.first_name object.user.username %}</p>
        <p>Promocode: <code>{{ object.promocode}}</code></p>
        <p>Delivery address: {{ object.delivery_address }}</p>
        <div>
            Product in order:
            <ul>
                {% for product in object.products.all  %}
                    <li>{{ product.name }}</li>
                {% endfor %}  
            </ul>
        </div>    
    </div>
    <div>
        <a href="{% url "shopapp:orders_list" %}">Back to order</a>
    </div>
{% endblock  %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order List
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url "shopapp:order_details" pk=order.pk %}"
                  >Details #{{ order.pk }}</a></p>
                <p>{% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode}}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Product in order:
                    <ul>
                      {% for product in order.products.all  %}
                         <li>{{ product.name }}</li>
                      {% endfor %}  
                    </ul>
                </div>
            </div>
        
        {% endfor %}
    </div>
  {% else %}
    <h3>No order yet</h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/product-detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock  %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
        <div>
            {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name}}">
            {% endif %}
        </div>
        <h3>Images</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                </div>
                <div>{{ img.description }}</div>
            {% empty %}
                <div>No images upload yet</div>
            {% endfor %}
        </div>

    </div>
    <div>
        <a href="{% url "shopapp:product_update" pk=product.pk %}">Update product</a>
    </div>
    <div>
        <a href="{% url "shopapp:product_delete" pk=product.pk %}">Archived product</a>
    </div>
    <div>
        <a href="{% url "shopapp:products_list" %}">Back to products list</a>
    </div>
{% endblock  %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}


{% block body %}
   <h1>Are you sure to archive {{ object.name }}</h1> 
   <br>
   <div>
    <a href="{% url "shopapp:product_detail" pk=object.pk %}"
    >Back to product</a>
   </div>
   <br>
   <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Archive</button>
    </form>
   </div>
{% endblock  %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
   Create product 
{% endblock  %}

{% block body %}
   <h1>Create product</h1> 
   <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}
        
        <button type="submit">
            Create
        </button>
    </form>
</div>
<div>
    <a href="{% url "shopapp:products_list" %}"
    >Back to products list</a>
</div>
{% endblock  %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
   Update product 
{% endblock  %}

{% block body %}
   <h1>Update product</h1> 
   <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}
        
        <button type="submit">
            Update
        </button>
    </form>
</div>
<div>
    <a href="{% url "shopapp:product_detail" pk=object.pk %}"
    >Back to products #{{ object.pk }}</a>
</div>
{% endblock  %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends "shopapp/base.html" %}

{% load i18n  %}

{% block title %}
    {% translate "Products list" %}
{% endblock  %}


{% block body %}
    <h1>{% translate "Products" %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count products_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ products_count }} products.
            {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url "shopapp:product_detail" pk=product.pk  %}"
                        >{% translate "Name" context "product name" %}: {{ product.name }}</a></p>
                    <p>{% translate "Price" %}: {{ product.price }}</p>
                    {% translate "no discount" as no_discount %}
                    <p>{% translate "Discount" %}: {% firstof product.discount no_discount %}</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name}}" width="150">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div>
            <a href="{% url "shopapp:product_create" %}"
            >{% translate "Create a new product" %}</a>
        </div>
    {% else %}
        {% url "shopapp:product_create" as create_product_url %}
        {% blocktranslate %}
         <h3>No products yet</h3> 
         <a href="{{ create_product_url }}"
          >Create a new one</a>
        {% endblocktranslate %}
    {% endif %}

    
{% endblock  %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url "admin:import_products_csv" %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock  %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends "shopapp/base.html" %}

{% block  title %}
    Shop Index
{% endblock  %}

{% block  body%}
    <h1>Hello Shop Index</h1>

    <div>
        <ul>
            {% for name, price in products %}
               <li>{{name}} for ${{price}}</li>
            {% empty%}
                No products here
            {% endfor %}
        </ul>
    </div>
    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>
{% endblock  %}